config/routes.rb
Rails.application.routes.draw do
  resources :projects

  get 'test01/index'

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :summary, :tag1, :tag2, :tag3, :tag4, :tag5, :tag6, :tag7, :tag8, :tag9, :tag10, :place, :url, :start_date, :member, :job, :skill_description, :skill_tag1, :skill_tag2, :skill_tag3, :skill_tag4, :skill_tag5, :skill_tag6, :skill_tag7, :skill_tag8, :skill_tag9, :skill_tag10, :owner_pic_url, :pic_position, :vision)
    end
end

app/controllers/test01_controller.rb
class Test01Controller < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/test01_helper.rb
module Test01Helper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "project_match" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "lumen", :media => "all" %>
  <%= stylesheet_link_tag "tag-it/jquery.tagit", :media => "all" %>

  <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

</head>
<body>


<%= yield %>





<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "lumen" %>
<%= javascript_include_tag "tag-it" %>
<%= yield(:page_javascript) if content_for?(:page_javascript) %>
</body>
</html>

app/views/projects/_form.html.erb
<div id="wrapper">
  <div id="header">
    <h2>Tag-it! Usage Examples</h2>

    <ul id="nav">
      <li><a href="http://aehlke.github.com/tag-it">&laquo; back to widget home</a></li>
    </ul>
  </div>

  <div id="content">
    <p>These demo various features of Tag-it. View the source to see how each works.</p>

    <hr>
    <h3>Minimal</h3>
    <form>
      <p>
        Vanilla example &mdash; the absolute minimum amount of code required, no configuration. No autocomplete, either. See the other examples for that.
      </p>
      <ul id="myTags"></ul>
      <input type="submit" value="Submit">
    </form>

    <hr>
    <h3>Single Input Field</h3>
    <form>
      <p>
        Example using a single input form field to hold all the tag values, instead of one per tag (see settings.singleField).
        This method is particularly useful if you have a form with one input field for comma-delimited tags that you want to trivially "upgrade" to this fancy jQuery UI widget.
        This configuration will also degrade nicely as well for browsers without JS &mdash; the default behavior is to have one input per tag, which does not degrade as well as one comma-delimited input.
      </p>
      <p>
        Normally this input field will be hidden &mdash; we leave it visible here so you can see how it is manipulated by the widget:
        <input name="tags" id="mySingleField" value="Apple, Orange" disabled="true"> <!-- only disabled for demonstration purposes -->
      </p>
      <ul id="singleFieldTags"></ul>
      <input type="submit" value="Submit">
    </form>

    <hr>
    <h3><a name="graceful-degredation"></a>Single Input Field (2)</h3>
    <form>
      <p>
        If you instantiate Tag-it on an INPUT element, it will default to being singleField, with that INPUT element as the singleFieldNode. This is the simplest way to have a gracefully-degrading tag widget.
      </p>
      <input name="tags" id="singleFieldTags2" value="Apple, Orange">
    </form>

    <hr>
    <h3>Spaces Allowed Without Quotes</h3>
    <p>You can already do multiword tags with spaces in them by default, but those must be wrapped in quotes. This option lets you use spaces without requiring the user to quote the input.</p>
    <p>There are normally 5 ways to insert a tag after inputting some text: space, comma, enter, selecting an autocomplete option, or defocusing the widget. With the "allowSpaces" option set to true, space no longer inserts a tag, it just adds a space to the current tag input.</p>
    <form>
      <p></p>
      <ul id="allowSpacesTags"></ul>
    </form>

    <hr>
    <h3>Preloading Data in Markup</h3>
    <form>
      <p>
        Using a UL in HTML to prefill the widget with some tags.
      </p>
      <ul id="myULTags">
        <!-- Existing list items will be pre-added to the tags. -->
        <li>Tag1</li>
        <li>Tag2</li>
      </ul>
    </form>

    <hr>

    <h3>Read-only</h3>
    <form>
      <p>Example of read only tags.</p>
      <ul id="readOnlyTags">
        <li>Tag1</li>
        <li>Tag2</li>
      </ul>
    </form>

    <hr>

    <h3>Events</h3>
    <form>
      <p>Example of tag events. Try adding or removing a tag, adding a duplicate tag, or clicking on a tag's label.</p>
      <ul id="eventTags">
        <li>Click my label</li>
        <li>Remove me</li>
      </ul>
    </form>
    <div id="events_container"></div>

    <hr>

    <h3>Methods</h3>
    <form>
      <p>Demos the available widget methods. Click the links below the widget to try them.</p>
      <ul id="methodTags"></ul>
      <p><a href="#" onclick="var inp=prompt('Enter a tag value to test the createTag method.');$('#methodTags').tagit('createTag', inp);return false;">Create tag</a></p>
      <p><a href="#" onclick="var inp=prompt('Enter a tag value to test the removeTagByName method.');$('#methodTags').tagit('removeTagByName', inp);return false;">Remove tag by name</a></p>
      <p><a href="#" onclick="$('#methodTags').tagit('removeAll');return false;">Clear tags</a></p>
    </form>

    <hr>
    <h3>Remove Confirmation</h3>
    <form>
      <p>
        When removeConfirmation is enabled the user has to press the backspace key twice to remove the last tag.
      </p>
      <ul id="removeConfirmationTags">
        <li>backspace me</li>
        <li>me too</li>
      </ul>
    </form>

  </div>


  <div id="footer">
    <div class="left">
      <p>Built with <a href="http://jquery.com/" target="_blank">jQuery</a> and <a href="http://jqueryui.com/" target="_blank">jQuery UI</a>.</p>
      <p>Originally created by <a href="http://levycarneiro.com/">Levy Carneiro Jr</a>. Currently maintained by <a href="http://github.com/aehlke">Alex Ehlke</a>.</p>
    </div>
    <p class="right weak">Template adopted from <a href="http://orderedlist.com/demos/fancy-zoom-jquery/">orderedlist.com</a></p>
    <br class="clear"/>
  </div>
</div>


<%= form_for @project, html: { class: "form-horizontal" }  do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <fieldset>

  <div class="form-group">




    <%= f.label :プロジェクト名, class: "col-lg-2 control-label" %><br>
    <div class="col-lg-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="field">
    <%= f.label :プロジェクト概要 %><br>
    <%= f.text_field :summary %>
  </div>

  <div class="field">
    <%= f.label :tag1 %><br>
    <%= f.text_field :tag1 %>
  </div>
  <div class="field">
    <%= f.label :tag2 %><br>
    <%= f.text_field :tag2 %>
  </div>
  <div class="field">
    <%= f.label :tag3 %><br>
    <%= f.text_field :tag3 %>
  </div>
  <div class="field">
    <%= f.label :tag4 %><br>
    <%= f.text_field :tag4 %>
  </div>
  <div class="field">
    <%= f.label :tag5 %><br>
    <%= f.text_field :tag5 %>
  </div>
  <div class="field">
    <%= f.label :tag6 %><br>
    <%= f.text_field :tag6 %>
  </div>
  <div class="field">
    <%= f.label :tag7 %><br>
    <%= f.text_field :tag7 %>
  </div>
  <div class="field">
    <%= f.label :tag8 %><br>
    <%= f.text_field :tag8 %>
  </div>
  <div class="field">
    <%= f.label :tag9 %><br>
    <%= f.text_field :tag9 %>
  </div>
  <div class="field">
    <%= f.label :tag10 %><br>
    <%= f.text_field :tag10 %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.number_field :place %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :member %><br>
    <%= f.text_field :member %>
  </div>
  <div class="field">
    <%= f.label :job %><br>
    <%= f.number_field :job %>
  </div>
  <div class="field">
    <%= f.label :skill_description %><br>
    <%= f.text_field :skill_description %>
  </div>
  <div class="field">
    <%= f.label :skill_tag1 %><br>
    <%= f.text_field :skill_tag1 %>
  </div>
  <div class="field">
    <%= f.label :skill_tag2 %><br>
    <%= f.text_field :skill_tag2 %>
  </div>
  <div class="field">
    <%= f.label :skill_tag3 %><br>
    <%= f.text_field :skill_tag3 %>
  </div>
  <div class="field">
    <%= f.label :skill_tag4 %><br>
    <%= f.text_field :skill_tag4 %>
  </div>
  <div class="field">
    <%= f.label :skill_tag5 %><br>
    <%= f.text_field :skill_tag5 %>
  </div>
  <div class="field">
    <%= f.label :skill_tag6 %><br>
    <%= f.text_field :skill_tag6 %>
  </div>
  <div class="field">
    <%= f.label :skill_tag7 %><br>
    <%= f.text_field :skill_tag7 %>
  </div>
  <div class="field">
    <%= f.label :skill_tag8 %><br>
    <%= f.text_field :skill_tag8 %>
  </div>
  <div class="field">
    <%= f.label :skill_tag9 %><br>
    <%= f.text_field :skill_tag9 %>
  </div>
  <div class="field">
    <%= f.label :skill_tag10 %><br>
    <%= f.text_field :skill_tag10 %>
  </div>
  <div class="field">
    <%= f.label :owner_pic_url %><br>
    <%= f.text_field :owner_pic_url %>
  </div>
  <div class="field">
    <%= f.label :pic_position %><br>
    <%= f.number_field :pic_position %>
  </div>
  <div class="field">
    <%= f.label :vision %><br>
    <%= f.text_field :vision %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </fieldset>
<% end %>


    <form class="form-horizontal">
      <fieldset>
        <legend>Legend</legend>
        <div class="form-group">
          <label for="inputEmail" class="col-lg-2 control-label">Email</label>
          <div class="col-lg-10">
            <input class="form-control" id="inputEmail" placeholder="Email" type="text">
          </div>
        </div>
        <div class="form-group">
          <label for="inputPassword" class="col-lg-2 control-label">Password</label>
          <div class="col-lg-10">
            <input class="form-control" id="inputPassword" placeholder="Password" type="password">
            <div class="checkbox">
              <label>
                <input type="checkbox"> Checkbox
              </label>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="textArea" class="col-lg-2 control-label">Textarea</label>
          <div class="col-lg-10">
            <textarea class="form-control" rows="3" id="textArea"></textarea>
            <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-2 control-label">Radios</label>
          <div class="col-lg-10">
            <div class="radio">
              <label>
                <input name="optionsRadios" id="optionsRadios1" value="option1" checked="" type="radio">
                Option one is this
              </label>
            </div>
            <div class="radio">
              <label>
                <input name="optionsRadios" id="optionsRadios2" value="option2" type="radio">
                Option two can be something else
              </label>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="select" class="col-lg-2 control-label">Selects</label>
          <div class="col-lg-10">
            <select class="form-control" id="select">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>
            <br>
            <select multiple="" class="form-control">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <button class="btn btn-default">Cancel</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </fieldset>
    </form>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to '一覧', @project %> |
<%= link_to '戻る', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th>Tag1</th>
      <th>Tag2</th>
      <th>Tag3</th>
      <th>Tag4</th>
      <th>Tag5</th>
      <th>Tag6</th>
      <th>Tag7</th>
      <th>Tag8</th>
      <th>Tag9</th>
      <th>Tag10</th>
      <th>Place</th>
      <th>Url</th>
      <th>Start date</th>
      <th>Member</th>
      <th>Job</th>
      <th>Skill description</th>
      <th>Skill tag1</th>
      <th>Skill tag2</th>
      <th>Skill tag3</th>
      <th>Skill tag4</th>
      <th>Skill tag5</th>
      <th>Skill tag6</th>
      <th>Skill tag7</th>
      <th>Skill tag8</th>
      <th>Skill tag9</th>
      <th>Skill tag10</th>
      <th>Owner pic url</th>
      <th>Pic position</th>
      <th>Vision</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.summary %></td>
        <td><%= project.tag1 %></td>
        <td><%= project.tag2 %></td>
        <td><%= project.tag3 %></td>
        <td><%= project.tag4 %></td>
        <td><%= project.tag5 %></td>
        <td><%= project.tag6 %></td>
        <td><%= project.tag7 %></td>
        <td><%= project.tag8 %></td>
        <td><%= project.tag9 %></td>
        <td><%= project.tag10 %></td>
        <td><%= project.place %></td>
        <td><%= project.url %></td>
        <td><%= project.start_date %></td>
        <td><%= project.member %></td>
        <td><%= project.job %></td>
        <td><%= project.skill_description %></td>
        <td><%= project.skill_tag1 %></td>
        <td><%= project.skill_tag2 %></td>
        <td><%= project.skill_tag3 %></td>
        <td><%= project.skill_tag4 %></td>
        <td><%= project.skill_tag5 %></td>
        <td><%= project.skill_tag6 %></td>
        <td><%= project.skill_tag7 %></td>
        <td><%= project.skill_tag8 %></td>
        <td><%= project.skill_tag9 %></td>
        <td><%= project.skill_tag10 %></td>
        <td><%= project.owner_pic_url %></td>
        <td><%= project.pic_position %></td>
        <td><%= project.vision %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<%= stylesheet_link_tag "projects", :media => "all" %>
<div class="container">
  <h1>プロジェクトの投稿</h1>

  <%= render 'form' %>

  <%= link_to '戻る', projects_path %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @project.summary %>
</p>

<p>
  <strong>Tag1:</strong>
  <%= @project.tag1 %>
</p>

<p>
  <strong>Tag2:</strong>
  <%= @project.tag2 %>
</p>

<p>
  <strong>Tag3:</strong>
  <%= @project.tag3 %>
</p>

<p>
  <strong>Tag4:</strong>
  <%= @project.tag4 %>
</p>

<p>
  <strong>Tag5:</strong>
  <%= @project.tag5 %>
</p>

<p>
  <strong>Tag6:</strong>
  <%= @project.tag6 %>
</p>

<p>
  <strong>Tag7:</strong>
  <%= @project.tag7 %>
</p>

<p>
  <strong>Tag8:</strong>
  <%= @project.tag8 %>
</p>

<p>
  <strong>Tag9:</strong>
  <%= @project.tag9 %>
</p>

<p>
  <strong>Tag10:</strong>
  <%= @project.tag10 %>
</p>

<p>
  <strong>Place:</strong>
  <%= @project.place %>
</p>

<p>
  <strong>Url:</strong>
  <%= @project.url %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>Member:</strong>
  <%= @project.member %>
</p>

<p>
  <strong>Job:</strong>
  <%= @project.job %>
</p>

<p>
  <strong>Skill description:</strong>
  <%= @project.skill_description %>
</p>

<p>
  <strong>Skill tag1:</strong>
  <%= @project.skill_tag1 %>
</p>

<p>
  <strong>Skill tag2:</strong>
  <%= @project.skill_tag2 %>
</p>

<p>
  <strong>Skill tag3:</strong>
  <%= @project.skill_tag3 %>
</p>

<p>
  <strong>Skill tag4:</strong>
  <%= @project.skill_tag4 %>
</p>

<p>
  <strong>Skill tag5:</strong>
  <%= @project.skill_tag5 %>
</p>

<p>
  <strong>Skill tag6:</strong>
  <%= @project.skill_tag6 %>
</p>

<p>
  <strong>Skill tag7:</strong>
  <%= @project.skill_tag7 %>
</p>

<p>
  <strong>Skill tag8:</strong>
  <%= @project.skill_tag8 %>
</p>

<p>
  <strong>Skill tag9:</strong>
  <%= @project.skill_tag9 %>
</p>

<p>
  <strong>Skill tag10:</strong>
  <%= @project.skill_tag10 %>
</p>

<p>
  <strong>Owner pic url:</strong>
  <%= @project.owner_pic_url %>
</p>

<p>
  <strong>Pic position:</strong>
  <%= @project.pic_position %>
</p>

<p>
  <strong>Vision:</strong>
  <%= @project.vision %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/test01/index.html.erb
<h1>Test01#index</h1>
<p>Find me in app/views/test01/index.html.erb</p>